version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:7.0-alpine3.17

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html
    depends_on:
      - redis

  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - redis
      - php
